pollster_map = {
    "American Res.Group" : "American Research Group",
    "American Research" : "American Research Group",
    "ARG" : "American Research Group",
    "NY Times" : "CBS / New York Times",
    "Chicago Tribune" : "Chicago Trib. / MarketShares",
    "Market Shares" : "Chicago Trib. / MarketShares",
    "CNN/Opinion Research" : "CNN / Opinion Research",
    "Opinion Res." : "CNN / Opinion Research",
    "Opinion Research" : "CNN / Opinion Research",
    "Columbus Dispatch" : "Columbus Dispatch (OH)",
    "Columbus Dispatch*" : "Columbus Dispatch (OH)",
    "EPIC/MRA" : "EPIC-MRA",
    "Fairleigh Dickinson" : "Fairleigh-Dickinson (NJ)",
    "Fairleigh Dickinson U." : "Fairleigh-Dickinson (NJ)",
    "Fairleigh Dickinson Univ." : "Fairleigh-Dickinson (NJ)",
    "Fairleigh-Dickinson Univ." : "Fairleigh-Dickinson (NJ)",
    "Field" : "Field Poll (CA)",
    "Field Poll" : "Field Poll (CA)",
    "Fox/Opinion Dyn." : "Fox / Opinion Dynamics",
    "Opinion Dynamics" : "Fox / Opinion Dynamics",
    "Franklin Pierce Coll." : "Franklin Pierce (NH)",
    "Inside Advantage" : "Insider Advantage",
    "InsiderAdvantage" : "Insider Advantage",
    "Keystone Poll" : "Keystone (PA)",
    "LA Times" : "LA Times / Bloomberg",
    "Los Angeles Times" : "LA Times / Bloomberg",
    "Bloomberg News" : "LA Times / Bloomberg",
    "Marist" : "Marist (NY)",
    "Marist Coll." : "Marist (NY)",
    "Marist College" : "Marist (NY)",
    "Mason-Dixon*" : "Mason-Dixon",
    "Mitchell Research" : "Mitchell",
    "Ohio Poll/Univ of Cin." : "Ohio Poll",
    "Ohio U." : "Ohio Poll",
    "Ohio Univ." : "Ohio Poll",
    "Pub. Opin. Strat." : "Public Opinion Strategies",
    "Pub. Opinion Strat." : "Public Opinion Strategies",
    "PPP (D)" : "Public Policy Polling (PPP)",
    "Quinnipiac U." : "Quinnipiac",
    "Quinnipiac Univ." : "Quinnipiac",
    "Quinnipiac Univ" : "Quinnipiac",
    "Rasmussen Reports" : "Rasmussen",
    #"" : "Research 2000",
    "Selzer & Co." : "Selzer",
    "Star Tribune" : "Star Tribune (MN)",
    "Star-Tribune" : "Star Tribune (MN)",
    #"" : "Strategic Vision",
    "Suffolk U." : "Suffolk (NH/MA)",
    "Suffolk Univ." : "Suffolk (NH/MA)",
    "Suffolk University" : "Suffolk (NH/MA)",
    "Survey USA" : "SurveyUSA",
    "U. of New Hampshire" : "Univ. New Hampshire",
    "Univ. of New Hampsh." : "Univ. New Hampshire",
    "Univ. of New Hampshire" : "Univ. New Hampshire",
    "Gallup" : "USA Today / Gallup",
    "Zogby" : "Zogby",
    #"" : "Zogby Interactive",
}
